### ISSUE TITLE
Problemas con fetch

### ISSUE THREAD

**Issue by MartaMolina01** [ULL-ESIT-DMSI-2223/intro2sd-marta-molina-fernandez-alu0101603360#10]
Buenos días @crguezl ;

he seguido trabajando en la práctica jekyll search y el problema actual es que parece fallar la conexión y en consecuencia el fetch de la página [Search](https://ull-esit-dmsi-2223.github.io/intro2sd-marta-molina-fernandez-alu0101603360/Search/)

Adjunto imagen:
![image](https://user-images.githubusercontent.com/83011996/209823011-636fc859-d3d5-493c-aced-1312edcb95fb.png)

¿Sabe qué es lo que está dando problemas?

Gracias. Un saludo.

**Comment by crguezl** [comment]
@MartaMolina01 

El error lo tienes  en el primer parámetro. Debes usar el `baseurl`:

```diff
➜  intro2sd-marta-molina-fernandez-alu0101603360 git:(main) ✗ git -P diff Search.md
diff --git a/Search.md b/Search.md
index 0274d69..d914796 100644
--- a/Search.md
+++ b/Search.md
@@ -27,7 +27,7 @@ title: Search
 <script type="text/javascript">
 
   const Search = new JekyllSearch(
-    '{{site.url}}/assets/src/Search.json',
+    '{{site.baseurl}}/assets/src/Search.json',
     '#Search',
     '#list',
     '{{site.baseurl}}'
```
