### ISSUE TITLE
Fin práctica Jekyll Search

### ISSUE THREAD

**Issue by MartaMolina01** [ULL-ESIT-DMSI-2223/intro2sd-marta-molina-fernandez-alu0101603360#11]
Buenas tardes @crguezl ;

Acabo de terminar el [resumen](https://ull-esit-dmsi-2223.github.io/intro2sd-marta-molina-fernandez-alu0101603360/summaries/chapter2/) del capítulo dos del libro Developing Information Systems. Además ya funciona correctamente la página [search](https://ull-esit-dmsi-2223.github.io/intro2sd-marta-molina-fernandez-alu0101603360/Search/). ¿Podría revisarlo para que todo esté correcto?

Muchas gracias. Un saludo.

**Comment by crguezl** [comment]
@MartaMolina01 

Lo veo bien. 

¿Podrías reutilizar la lupa de la *navbar* para que te llevara a la página de búsqueda o simplemente suprimirla?.
