### ISSUE TITLE
Duda jekyll search

### ISSUE THREAD

**Issue by MartaMolina01** [ULL-ESIT-DMSI-2223/intro2sd-marta-molina-fernandez-alu0101603360#8]
Buenas tardes @crguezl ;

Estaba haciendo la práctica de Jekyll Search y tras crear los archivos, escribir el código y desplegar la página, en la [page search](https://ull-esit-dmsi-2223.github.io/intro2sd-marta-molina-fernandez-alu0101603360/search/) me salió esto que no sé que tipo de error es:

![image](https://user-images.githubusercontent.com/83011996/207656031-aedfbd8d-0817-4931-81d5-aed86f3c2203.png)

**Comment by crguezl** [comment]
@MartaMolina01 

Parece que tienes mal sangrado en el `search.md` el `script` tag.

Ten en cuenta que en markdown un sangrado de mas de dos significa verbatim.
