### ISSUE TITLE
Problemas Jekyll search

### ISSUE THREAD

**Issue by MartaMolina01** [ULL-ESIT-DMSI-2223/intro2sd-marta-molina-fernandez-alu0101603360#9]
Buenas tardes @crguezl ;

escribo este issue por que el programa crea correctamente la página de [Jekyll Search](https://ull-esit-dmsi-2223.github.io/intro2sd-marta-molina-fernandez-alu0101603360/search/) pero a la hora de escribir la búsqueda, no busca automáticamente, solo sale la búsqueda de lo escrito en el cuadrito en la url si le das al enter. Y cuando pulsas enter aún así no se crea una lista con las coincidencias encontradas.

Gracias. Un saludo.

**Comment by crguezl** [comment]
@MartaMolina01 

En el fichero `search.md` dice:

```js
<script type="text/javascript" src="/assets/src/fetch.js"></script>
<script type="text/javascript" src="/assets/src/search.js"></script>
```

como se ve, la url apunta a la raíz sin tener en cuenta el base url, así que no está encontrando los scripts como puede comprobarse usando las developer tools:
<img width="1788" alt="Captura de pantalla 2022-12-20 a las 10 08 51" src="https://user-images.githubusercontent.com/1142554/208641478-1ad58f71-f271-4990-81c0-1cbb4a32ddf1.png">
